/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorCompra;
import controlador.ControladorOferta;
import controlador.ControladorProducto;
import controlador.ControladorUsuario;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Gustavo
 */
public class Diagnostico extends javax.swing.JFrame {

    /**
     * Creates new form Diagnostico
     */
    public Diagnostico() {
        initComponents();
        
        //        Icono
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconox.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jBDolorCabeza = new javax.swing.JButton();
        jBDolorEst = new javax.swing.JButton();
        jBInfl = new javax.swing.JButton();
        jBDolorBoca = new javax.swing.JButton();
        jBDolorEspalda = new javax.swing.JButton();
        jBFiebre = new javax.swing.JButton();
        jBTos = new javax.swing.JButton();
        jBPiel = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPInformacion = new javax.swing.JTextPane();
        lblAdv = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBDolorCabeza.setBackground(new java.awt.Color(0, 0, 51));
        jBDolorCabeza.setForeground(new java.awt.Color(204, 204, 204));
        jBDolorCabeza.setText("Dolor de cabeza");
        jBDolorCabeza.setBorder(null);
        jBDolorCabeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDolorCabezaActionPerformed(evt);
            }
        });
        jPanel1.add(jBDolorCabeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, -1));

        jBDolorEst.setBackground(new java.awt.Color(0, 0, 51));
        jBDolorEst.setForeground(new java.awt.Color(204, 204, 204));
        jBDolorEst.setText("Dolor estomacal");
        jBDolorEst.setBorder(null);
        jBDolorEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDolorEstActionPerformed(evt);
            }
        });
        jPanel1.add(jBDolorEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, -1));

        jBInfl.setBackground(new java.awt.Color(0, 0, 51));
        jBInfl.setForeground(new java.awt.Color(255, 255, 255));
        jBInfl.setText("Inflamación corporal");
        jBInfl.setBorder(null);
        jBInfl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInflActionPerformed(evt);
            }
        });
        jPanel1.add(jBInfl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, -1));

        jBDolorBoca.setBackground(new java.awt.Color(0, 0, 51));
        jBDolorBoca.setForeground(new java.awt.Color(255, 255, 255));
        jBDolorBoca.setText("Dolor de boca");
        jBDolorBoca.setBorder(null);
        jBDolorBoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDolorBocaActionPerformed(evt);
            }
        });
        jPanel1.add(jBDolorBoca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, -1));

        jBDolorEspalda.setBackground(new java.awt.Color(0, 0, 51));
        jBDolorEspalda.setForeground(new java.awt.Color(204, 204, 204));
        jBDolorEspalda.setText("Dolor de espalda");
        jBDolorEspalda.setBorder(null);
        jBDolorEspalda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDolorEspaldaActionPerformed(evt);
            }
        });
        jPanel1.add(jBDolorEspalda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, -1));

        jBFiebre.setBackground(new java.awt.Color(0, 0, 51));
        jBFiebre.setForeground(new java.awt.Color(204, 204, 204));
        jBFiebre.setText("Fiebre");
        jBFiebre.setBorder(null);
        jBFiebre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFiebreActionPerformed(evt);
            }
        });
        jPanel1.add(jBFiebre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 150, -1));

        jBTos.setBackground(new java.awt.Color(0, 0, 51));
        jBTos.setForeground(new java.awt.Color(204, 204, 204));
        jBTos.setText("Tos");
        jBTos.setBorder(null);
        jBTos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTosActionPerformed(evt);
            }
        });
        jPanel1.add(jBTos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 150, -1));

        jBPiel.setBackground(new java.awt.Color(0, 0, 51));
        jBPiel.setForeground(new java.awt.Color(204, 204, 204));
        jBPiel.setText("Afección a la piel");
        jBPiel.setBorder(null);
        jBPiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPielActionPerformed(evt);
            }
        });
        jPanel1.add(jBPiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 150, -1));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 150, 10));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 112, 150, 10));

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, 10));

        jSeparator5.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, 10));

        jSeparator6.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 150, 10));

        jSeparator7.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 150, 10));

        jSeparator8.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 150, 10));

        jSeparator9.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 150, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Pharma Link");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 220, 580));

        jPanel3.setBackground(new java.awt.Color(0, 30, 84));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTPInformacion.setEditable(false);
        jTPInformacion.setBackground(new java.awt.Color(0, 30, 84));
        jTPInformacion.setBorder(null);
        jTPInformacion.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTPInformacion);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 438, 240));

        lblAdv.setForeground(new java.awt.Color(204, 0, 0));
        lblAdv.setText("ADVERTENCIA:");
        jPanel3.add(lblAdv, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("La información proporcionada es la estimada por la farmacia,");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("y recomendamos productos que no requieran medicación");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 349, -1));

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Para mas información consulte a un especialista.");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 840, 470));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_2/icons8_go_back_32px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 50));

        jPanel2.setBackground(new java.awt.Color(195, 204, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Diagnóstico virtual");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_2/icons8_x-ray_32px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(544, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBDolorCabezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDolorCabezaActionPerformed
        jTPInformacion.setText("");
        jTPInformacion.setText("Los dolores de cabeza pueden tener causas que no se deben a una enfermedad subyacente."
                            + " Por ejemplo, falta de sueño, aumento incorrecto de los anteojos recetados, exposición a"
                            + " ruidos fuertes o uso de gorros o sombreros ajustados.\n"
                            + " Recomendación:\n"
                            + " Si eres mayor de 16 años 1 comprimido (500 mg de ácido acetilsalicílico) cada 4 ó 6 horas,"
                            + " si fuera necesario.");
    }//GEN-LAST:event_jBDolorCabezaActionPerformed

    private void jBDolorEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDolorEstActionPerformed
        jTPInformacion.setText("");
        jTPInformacion.setText("El dolor abdominal puede tener causas que no se deben a una enfermedad subyacente. "
                            + "Por ejemplo, constipación, gases, comer en exceso, estrés o distensión muscular.\n"
                            + "Recomendación:\n"
                            + "Le recomendamos tomar Gaviscon.\n "
                            + "La dosis normal en adultos, incluyendo ancianos y adolescentes mayores de 12 años,"
                            + " es de 1 a 2 sobres, según necesidad, 1 hora después de las comidas y antes de acostarse."
                            + " Como máximo puede tomar 8 sobres en 24 horas. Cómo tomar: Este medicamento se toma por vía oral");
        
    }//GEN-LAST:event_jBDolorEstActionPerformed

    private void jBInflActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInflActionPerformed
        jTPInformacion.setText("");
        jTPInformacion.setText("Recomendacion: El ibuprofeno es un antiinflamatorio no esteroideo, utilizado frecuentemente como antipirético,"
                            + " analgésico y antiinflamatorio. \n"                           
                            + "El uso del Ibuprofeno es sin exceder de los 2,4 g diarios. Para el alivio del dolor leve a moderado y cuadros febriles,"
                            + "la dosis usual en adultos es de 400 mg cada 4 a 6 horas");
    }//GEN-LAST:event_jBInflActionPerformed

    private void jBDolorBocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDolorBocaActionPerformed
        jTPInformacion.setText("");
        jTPInformacion.setText("Recomedación: Para el dolor de muelas es el Ibuprofeno y el Nefersil"
                            + "Se ha demostrado que el Nefersil es más eficaz contra dolores / inflamaciones "
                            + "ya que al igual que el Ibuprofeno inhibe la produccion de la encimas pero este ultimo requiere de"
                            + "receta médica.\n"
                            + "en caso de comprar ibuprofeno el uso del Ibuprofeno es sin exceder de los 2,4 g diarios. Para el alivio del dolor leve a moderado y cuadros febriles,"
                            + "la dosis usual en adultos es de 400 mg cada 4 a 6 horas");
    }//GEN-LAST:event_jBDolorBocaActionPerformed

    private void jBDolorEspaldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDolorEspaldaActionPerformed
        jTPInformacion.setText("");
        jTPInformacion.setText("El dolor de espalda puede tener causas que no se deben a una enfermedad subyacente. Por ejemplo, realizar demasiado ejercicio, "
                + "levantar peso excesivo, estar sentado o acostado durante mucho tiempo,"
                + " dormir en una posición incómoda o usar una mochila inadecuada.\n" 
                + "Se recomienda consumir un analgesico, como ibuprofeno, paracetamol o naproxeno (400mg cada 4 a 6 horas en adultos, 50mg en niños) para aliviar la molestia");
    }//GEN-LAST:event_jBDolorEspaldaActionPerformed

    private void jBFiebreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFiebreActionPerformed
        jTPInformacion.setText("");
        jTPInformacion.setText("Aumento temporal de la temperatura corporal promedio, que suele ser de 37 °C, genera sudoración, sensación de frio, dolor de cabeza, perdida de apetito, debilidad general, etc.\n" +
                                "\n" +
                                "Se recomienda consumir medicamentos de venta libre tales como paracetamol (cada 4 a 6 horas) o ibuprofeno (cada 6 a 8 horas), 400mg en adultos, 50mg en niños");
    }//GEN-LAST:event_jBFiebreActionPerformed

    private void jBTosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTosActionPerformed
        jTPInformacion.setText("");
        jTPInformacion.setText("La tos puede tener causas que no se deben a una enfermedad subyacente. Por ejemplo, despejar normalmente las vías respiratorias, los irritantes, como el humo o el gas, el uso de tabaco o tragar incorrectamente alimentos o líquido, genera dificultad al hablar,\n" +
                                "al respirar, al tragar.\n" +
                                "\n" +
                                "Se recomiendo consumir medicamentos tales como aerosoles para calmar el dolor (diclocina o fenol), Analgésicos (paracetamol, ibuprofeno, naproxeno)");
    }//GEN-LAST:event_jBTosActionPerformed

    private void jBPielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPielActionPerformed
        jTPInformacion.setText("");
        jTPInformacion.setText("Cualquier cosa que irrite, obstruya o inflame la piel puede causar síntomas como enrojecimiento, hinchazón, ardor y picazón. La alergia, irritantes, su composición genética y ciertas enfermedades y problemas del sistema inmunitario pueden provocar sarpullido, urticaria y otros problemas en la piel. Muchos problemas de la piel, como el acné, también afectan su apariencia. \n" +
"\n" +
"Se recomienda utilizar cremas humectantes para utilizar en la zona problematica.");
    }//GEN-LAST:event_jBPielActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menú m = new Menú();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnostico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBDolorBoca;
    public javax.swing.JButton jBDolorCabeza;
    public javax.swing.JButton jBDolorEspalda;
    public javax.swing.JButton jBDolorEst;
    public javax.swing.JButton jBFiebre;
    public javax.swing.JButton jBInfl;
    public javax.swing.JButton jBPiel;
    public javax.swing.JButton jBTos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTextPane jTPInformacion;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAdv;
    // End of variables declaration//GEN-END:variables
}
