/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorUsuario;
import controlador.ControladorOferta;
import controlador.ControladorProducto;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.UsuarioSQL;

/**
 *
 * @author Eduardo
 */
public class IniciarSesion extends javax.swing.JFrame {    
    UsuarioSQL daoU = new UsuarioSQL();
    
    public IniciarSesion() {
        initComponents();
        
        //        Icono
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconox.png")).getImage());
        
        //        Titulo
        setTitle("INICIAR SESIÓN");
        
        //        Fondo del Jframe
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/f1.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        
        //        Centrar Jframe
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        InicioSesion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPContraseña = new javax.swing.JPasswordField();
        BTLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        FarmaciaLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 158, -1, -1));

        InicioSesion.setBackground(new java.awt.Color(0, 42, 113));
        InicioSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        InicioSesion.setForeground(new java.awt.Color(0, 42, 113));
        InicioSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rut:");
        InicioSesion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 44, 50));

        jPContraseña.setBackground(new java.awt.Color(0, 42, 113));
        jPContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jPContraseña.setBorder(null);
        InicioSesion.add(jPContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 159, 30));

        BTLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gustavo\\Desktop\\img\\V2inicFoto.png")); // NOI18N
        BTLogin.setBorder(null);
        BTLogin.setBorderPainted(false);
        BTLogin.setContentAreaFilled(false);
        BTLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTLoginActionPerformed(evt);
            }
        });
        InicioSesion.add(BTLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        InicioSesion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        InicioSesion.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 160, 20));

        getContentPane().add(InicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 600));

        jPanel1.setBackground(new java.awt.Color(195, 204, 204));
        jPanel1.setForeground(new java.awt.Color(195, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FarmaciaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_2/Profej.jpg"))); // NOI18N
        jPanel1.add(FarmaciaLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 550, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 460, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTLoginActionPerformed
        
    }//GEN-LAST:event_BTLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       IniciarSesion lg = new IniciarSesion();
        ControladorUsuario c = new ControladorUsuario(lg);
        lg.setVisible(true);
        lg.setLocationRelativeTo(lg);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTLogin;
    private javax.swing.JLabel FarmaciaLogo;
    private javax.swing.JPanel InicioSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPasswordField jPContraseña;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
